In [3]:
import pandas as pd
import numpy as np


df = pd.DataFrame(np.arange(1,11).reshape(2,5),index=["r1","r2"],columns=["c1","c2","c3","c4","c5"])


df.head()

    c1  c2  c3  c4  c5
r1   1   2   3   4   5
r2   6   7   8   9  10

In [4]:
df.to_csv("sample2.csv")

In [5]:
pd.read_csv("sample2.csv")

  Unnamed: 0  c1  c2  c3  c4  c5
0         r1   1   2   3   4   5
1         r2   6   7   8   9  10

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, r1 to r2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      2 non-null      int64
 1   c2      2 non-null      int64
 2   c3      2 non-null      int64
 3   c4      2 non-null      int64
 4   c5      2 non-null      int64
dtypes: int64(5)
memory usage: 96.0+ bytes

In [7]:
df.describe()

             c1        c2        c3        c4         c5
count  2.000000  2.000000  2.000000  2.000000   2.000000
mean   3.500000  4.500000  5.500000  6.500000   7.500000
std    3.535534  3.535534  3.535534  3.535534   3.535534
min    1.000000  2.000000  3.000000  4.000000   5.000000
25%    2.250000  3.250000  4.250000  5.250000   6.250000
50%    3.500000  4.500000  5.500000  6.500000   7.500000
75%    4.750000  5.750000  6.750000  7.750000   8.750000
max    6.000000  7.000000  8.000000  9.000000  10.000000

In [8]:
pd.read_csv("sample2.csv",sep = ",")

  Unnamed: 0  c1  c2  c3  c4  c5
0         r1   1   2   3   4   5
1         r2   6   7   8   9  10

In [11]:
import numpy as np
from io import StringIO
data =("a,b,c,d\n"
      "1,2,3,4\n"
      "5,6,7,8\n")

vf = pd.read_csv(StringIO(data),dtype={'b':int,"c":float})

In [12]:
vf

   a  b    c  d
0  1  2  3.0  4
1  5  6  7.0  8

In [15]:
js = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header = None)
js.head()

   0      1     2     3     4    5     6     7     8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   735

In [16]:
js.to_csv("js.csv")